// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	di "github.com/kuetix/container"
	"github.com/kuetix/engine/engine/defines"
	"github.com/kuetix/engine/engine/workflow"
	transitionsStock "github.com/acme-kuetix/acme-stock/modules/stock/transitions"
)

func init() {
	di.Boot()
	di.DependencyInjection["stock"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"stock"+"/"+"stock", func() interface{} { return workflow.ServiceTransitionMapping{ ServiceName: name, Name: "stock", Impl: transitionsStock.NewStockTransitions() }})
	}
}
